name: Releaser

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  npm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json
      - uses: home-lang/pantry/packages/action@main
      - run: bun install --frozen-lockfile
      - run: pantry publish --npm --access public
      - uses: stacksjs/action-releaser@v1.2.11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
